### ISSUE TITLE
croppedRef undefined

### ISSUE THREAD

**Issue by ionistrati** [giacomocerquone/react-perspective-cropper#15]
Hi @giacomocerquone,

I'm implementing this feature in a React app with typescript, and I can't initialize the croppedRef, I noticed in the files it is React.ElementRef with no children type, but it does require this ElementRef<{specific type}>.

Because of that, I can't call `done` method to crop the image.

I saw on npmjs it has the TypeScript icon, but I haven't seen a @types package, as I understand it's there because of the interface with props, but I can't inherit type of ref or anything.

Any ideas?

**Comment by ionistrati** [comment]
found the problem, cropperRef isn't really the component's ref, you just use `ref` and ignore the `cropperRef` prop, this is very strange.

**Comment by giacomocerquone** [comment]
> found the problem, cropperRef isn't really the component's ref, you just use `ref` and ignore the `cropperRef` prop, this is very strange.

How could it be the react's element ref if I needed to expose the done and backToCrop methods?
Don't get confused, a while ago there might have been a 1 to 1 match between react's elements and react refs.
Since hooks have landed, though, a ref is a much more wider concept: "a mutable escape hatch inside the react immutable world"

![image](https://user-images.githubusercontent.com/9303791/129905378-d2cd5e16-091f-4fc7-b549-b1ba5bebc373.png)

From https://overreacted.io/how-are-function-components-different-from-classes/

**Comment by giacomocerquone** [comment]
> Hi @giacomocerquone,
> 
> I'm implementing this feature in a React app with typescript, and I can't initialize the croppedRef, I noticed in the files it is React.ElementRef with no children type, but it does require this ElementRef<{specific type}>.
> 
> Because of that, I can't call `done` method to crop the image.
> 
> I saw on npmjs it has the TypeScript icon, but I haven't seen a @types package, as I understand it's there because of the interface with props, but I can't inherit type of ref or anything.
> 
> Any ideas?

If you have any problems with the types let me know. The lib isn't developed in ts as you noticed, though it has its types definition directly in the package (therefore no need to install @types/...).

**Comment by ionistrati** [comment]
> If you have any problems with the types let me know. The lib isn't developed in ts as you noticed, though it has its types definition directly in the package (therefore no need to install @types/...).

Yes, it has types inside, but @types library inherit any type from variables that come from the inside of your component, notify at mismatches and stuff like this.

**Comment by ionistrati** [comment]
> How could it be the react's element ref if I needed to expose the done and backToCrop methods?
> Don't get confused, a while ago there might have been a 1 to 1 match between react's elements and react refs.
> Since hooks have landed, though, a ref is a much more wider concept: "a mutable escape hatch inside the react immutable world"
> 
> ![image](https://user-images.githubusercontent.com/9303791/129905378-d2cd5e16-091f-4fc7-b549-b1ba5bebc373.png)
> 
> From https://overreacted.io/how-are-function-components-different-from-classes/

About this, what is the usage for cropperRef then?

**Comment by giacomocerquone** [comment]
> > How could it be the react's element ref if I needed to expose the done and backToCrop methods?
> > Don't get confused, a while ago there might have been a 1 to 1 match between react's elements and react refs.
> > Since hooks have landed, though, a ref is a much more wider concept: "a mutable escape hatch inside the react immutable world"
> > ![image](https://user-images.githubusercontent.com/9303791/129905378-d2cd5e16-091f-4fc7-b549-b1ba5bebc373.png)
> > From https://overreacted.io/how-are-function-components-different-from-classes/
> 
> About this, what is the usage for cropperRef then?

To expose the done and backtocrop methods, check the examples

**Comment by giacomocerquone** [comment]
> > If you have any problems with the types let me know. The lib isn't developed in ts as you noticed, though it has its types definition directly in the package (therefore no need to install @types/...).
> 
> Yes, it has types inside, but @types library inherit any type from variables that come from the inside of your component, notify at mismatches and stuff like this.

Didn't get this. What do you mean by the "type library"? Are you referring about the "definitely typed" project (which isn't a library) right? In that case I'm still not getting it since there is no @types/react-perspective-cropper published type so I don't understand where are the conflicts you're taking about

**Comment by ionistrati** [comment]
> > > If you have any problems with the types let me know. The lib isn't developed in ts as you noticed, though it has its types definition directly in the package (therefore no need to install @types/...).
> > 
> > 
> > Yes, it has types inside, but @types library inherit any type from variables that come from the inside of your component, notify at mismatches and stuff like this.
> 
> Didn't get this. What do you mean by the "type library"? Are you referring about the "definitely typed" project (which isn't a library) right? In that case I'm still not getting it since there is no @types/react-perspective-cropper published type so I don't understand where are the conflicts you're taking about

For example, with typescript, you can't create a `useRef` for cropperRef, because it won't trigger if you don't match the type for reference, and it comes as undefined, the workaround I found was to add a @ts-ignore, and to pass `ref` instead of `cropperRef` to the component. In this way I can get the done and backToCrop methods.

About the @types/react-perspective-cropper, I meant that every "passable" parameter should be typed, so you can inherit this in the parent component to prevent mismatches, because the .done and .backToCrop methods are callable, but typescript doesn't see them, I had to use ts-ignore to get the methods from component, and ts-ignore to use them.
